```{r data generation, echo = FALSE, results = "hide"}

Q = sample(1:4,1)
sig.level = sample(c(.05,.10),1)
Q1 = sample(1:3,1)

D1 = list('religious affiliation' = 
           c("Protestant", "Catholic", "Jewish", "Others"),
         'computer' = 
           c("iPad", "Notebook", "Desktop"),
         'major' = 
           c("Math/Science", "Arts and Humanities", "Business and Economics", "Others"),
         'pet' = 
           c("Fish", "Meat", "Vegetarian")
         )

D2 = list('shoe' = 
           c("Nike",	"Converse",	"Other"),
         'car' = 
           c("Sedan",	"SUV",	"Truck"),
         'sex' = 
           c("Male", "Female"),
         'dessert' = 
           c("Cake", "Ice Cream", "Pie")
         )

  N1 = lengths(D1)
  N2 = lengths(D2)

simulate.date <- function(j, Col=D1, Row=D2){
  N1 = lengths(Col)
  N2 = lengths(Row)
  col.dist = lapply(N1, function(x) sample(20:100,size = x)) %>% 
    lapply(function(x) round(x/sum(x),3))
  sim.data <- NULL
  idependent <- sample(c(T,F),size = 1,prob = c(.25,.75))
  for(i in 1:N2[j]){
    if(idependent){
      col.dist = lapply(N1, function(x) sample(20:100,size = x)) %>% 
          lapply(function(x) round(x/sum(x),3))
    }
    row.total <- sample(20:120,1)
    sim.data <- 
      rbind(sim.data,
            sapply(
              col.dist[[j]],
              FUN = function(x) round(sum(rbinom(n = 1000,size = 1,prob = x))/1000*row.total)
            ))
  }
  colnames(sim.data) <- Col[[j]]
  rownames(sim.data) <- Row[[j]]
  return(sim.data)
}

sim.data <- simulate.date(Q)
test.out <- chisq.test(x = sim.data) %>% suppressMessages()


  
q.text <- 
      list('religious affiliation' = 
           "A researcher is interested in investigating whether religious affiliation and the brand of sneakers that people wear are dependent. The table below shows the results of a survey.",
         'computer' = 
           "You are interested in investigating whether the type of computer a person primarily uses and the type of car they drive are dependent. The table below shows the results of a survey.",
         'major' = 
           "You are interested in investigating whether gender and major are independent at your college. The table below shows the results of a survey.",
         'pet' = 
           "A restaurant manager is interested in investigating whether the main course ordered and the dessert ordered are dependent. The table below shows the results of a survey."
         )

q.text1 <- list(
  'chi2stat' = "Calculate the Chi Squared test statistic for the test of independence.",
  'deg.free' = "Determine the number of degrees of freedom in the distribution of the Chi Squared test statistic for the test of independence.",
  'p.value' = "Calculate the p-value for the test of independence."
)

q.ans <- list(
  'chi2stat' = test.out$statistic,
  'deg.free' = (N1[Q]-1)*(N2[Q]-1),
  'p.value' = test.out$p.value
)

q.solution <- list(
  'chi2stat' = paste0("Chi Squared test statistic is ", fmt(q.ans[[1]], 3)),
  'deg.free' = paste0("The number of degrees of freedom is ", fmt(q.ans[[2]], 0)),
  'p.value' = paste0("The number of p-value is ", fmt(q.ans[[3]], 3))
)

load.data <- c(sim.data)
```


Question
========

`r q.text[[Q]]`

`r kable(sim.data)`

Use the R window below:

```{r,echo=FALSE,results='asis'}
paste0("dat <- matrix(c(", 
        paste(load.data,collapse =", "),
       "), nrow = ",
       N2[Q],
       ")"
      ) %>% rdrr.io()
```

**Hints:**

[Link to Text Book](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book:_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)/12:_Categorical_Data_Analysis/12.02:_The_2_test_of_independence_(or_association)){target="blank"} 

**Question:**

`r q.text1[[Q1]]`

Solution
========
`r q.solution[[Q1]]`

Meta-information
================
extype: num
exsolution: `r fmt(q.ans[[Q1]], 3)`
exname: chi2independence1
extol: `r fmt(ex_tol, 3)`



