```{r data generation, echo = FALSE, results = "hide"}

U = sample(c(TRUE,FALSE),1)
N = sample(5:7,1)
Q =  sample(1:3,1)

sim.data <- function(n, uniform = T){
   if(uniform){ 
    sample(10:100,1) %>% 
    rep(n) +
    sample(-10:20,n,replace = F) %>% 
    return()
   } else {
    sample(30:70,n) %>% 
    return()  
   }
}
D = c("Monday",	"Tuesday",	"Wednesday",	"Thursday",	"Friday",	"Saturday","Sunday")
q.data <- data.frame(
  'Day' = D[1:N],
  'Frequency' = sim.data(n = N,uniform = U)
)
observed = q.data$Frequency
expected = rep(sum(observed)/N, N)
chi2stat = sum( (observed - expected)^2 / expected )

q.text <- list(
  'chi2stat' = "Calculate the Chi Squared test statistic for the test that calls are received uniformly through out the week.",
  'deg.free' = "Determine the number of degrees of freedom in the distribution of the Chi Squared test statistic for the test that calls are received uniformly through out the week.",
  'p.value' = "Calculate the p-value for the test that calls are received uniformly through out the week."
)

q.ans <- list(
  'chi2stat' = chi2stat,
  'deg.free' = N - 1,
  'p.value' = pchisq(q=chi2stat,df=N-1,lower.tail = FALSE)
)

 q.solution <- list(
'chi2stat' = paste0("Chi Squared test statistic is ", fmt(q.ans[[1]], 3)),
'deg.free' = paste0("The number of degrees of freedom is ", fmt(q.ans[[2]], 0)),
'p.value' = paste0("The number of p-value is ", fmt(q.ans[[3]], 3))
)

```


Question
========

A call center receives calls through out week. The following is day of the week for a random sample of phone calls.

`r kable(q.data)`

Use the R window below:

```{r,echo=FALSE,results='asis'}
paste0("observed <- c(", 
        paste(observed,collapse =", "),
       ")"
      ) %>% rdrr.io()
```

**Hints:**

[Link to Text Book](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)/12%3A_Categorical_Data_Analysis/12.01%3A_The_2_Goodness-of-fit_Test?contentOnly "LSR - 12.1: The χ2 Goodness-of-fit Test"){target="blank"}

**Question:**

`r q.text[[Q]]`

Solution
========

`r q.solution[[Q]]`

Meta-information
================
extype: num
exsolution: `r fmt(q.ans[[Q]], 3)`
exname: chi2uniform
extol: `r fmt(ex_tol, 3)`

