```{r data generation, echo = FALSE, results = "hide"}

U = sample(c(1.5,3),1)
Q =  sample(1:4,1)
sig.level = sample(c(.05,.10),1)
Q1 = sample(1:3,1)

D = list('major' = 
           c("Math/Science", "Arts and Humanities", "Business and Economics", "Others"),
         'race' = 
           c("White", "Hispanic", "Black", "Other"),
         'party' = 
           c("Democrat", "Republican", "Independent/Other"),
         'residency' = 
           c("Dorm", "Apartment", "Live at Home")
         )

N = lengths(D)

q.dist = 
  lapply(N, function(x) sample(20:100,size = x))
q.dist = 
  lapply(q.dist, function(x) round(x/sum(x),3))
q.dist = 
  lapply(q.dist, function(x) x/sum(x))

sim.data =
  lapply(q.dist, function(x) round(x * sample(20:300,1) ,0))

sim.data =
  lapply(sim.data, function(x) 
    abs(round(x + sample(round(-U*sd(x)):round(U*sd(x)),length(x),replace = T) ,0)))

q.data <- data.frame(
  'Catagory' = D[[Q]],
  'Frequency' = sim.data[[Q]]
)
q.distrobution <- data.frame(
  'Catagory' = D[[Q]],
  'Percent' = round(q.dist[[Q]]*100,2)
)
observed = q.data$Frequency
expected = q.dist[[Q]]

test.out <- chisq.test(x = observed, p = expected)


  
q.text <- 
      list('major' = 
           "The distribution of majors at the college is shown in Table A. Suppose a random sample of athletes from the college are surveyed. The Table B shows the results of the survey.",
         'race' = 
           "The racial distribution for the state is shown in Table A. You are interested in seeing if the distribution at your college fits the distribution of the state. The Table B shows the results of the survey of students from your college.",
         'party' = 
           "The distribution of political affiliation in California is shown in Table A. Suppose a random sample of Californians who own their own homes are surveyed. The Table B shows the results of the survey.",
         'residency' = 
           "The statewide distribution of type of residency for students is given in Table A. Suppose a random sample of students from your college are surveyed. The Table B shows the results of the survey."
         )

q.text1 <- list(
  'chi2stat' = "Calculate the Chi Squared test statistic for the test of goodness of fit.",
  'deg.free' = "Determine the number of degrees of freedom in the distribution of the Chi Squared test statistic for the test of goodness of fit.",
  'p.value' = "Calculate the p-value for the test of goodness of fit."
)

q.ans <- list(
  'chi2stat' = test.out$statistic,
  'deg.free' = N[Q]-1,
  'p.value' = test.out$p.value
)

q.solution <- list(
  'chi2stat' = paste0("Chi Squared test statistic is ", fmt(q.ans[[1]], 3)),
  'deg.free' = paste0("The number of degrees of freedom is ", fmt(q.ans[[2]], 0)),
  'p.value' = paste0("The number of p-value is ", fmt(q.ans[[3]], 3))
)

```


Question
========

`r q.text[[Q]]`

**Table A**

`r kable(q.data)`

**Table B**
`r kable(q.distrobution)`

Use the R window below:

```{r,echo=FALSE,results='asis'}
paste0("observed <- c(", 
        paste(observed,collapse =", "),
       ")\n",
       "expected <- c(", 
        paste(round(expected,4),collapse =", "),
       ")"
      ) %>% rdrr.io()
```

**Hints:**

[Link to Text Book](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)/12%3A_Categorical_Data_Analysis/12.01%3A_The_2_Goodness-of-fit_Test?contentOnly "LSR - 12.1: The χ2 Goodness-of-fit Test"){target="blank"}

**Question:**

`r q.text1[[Q1]]`

Solution
========
`r q.solution[[Q1]]`

Meta-information
================
extype: num
exsolution: `r fmt(q.ans[[Q1]], 3)`
exname: chi2goodfit1
extol: `r fmt(ex_tol, 3)`



