---
knit: (function(inputFile, encoding) {
    rmarkdown::render(inputFile, encoding = encoding, output_dir = "../docs/")
  })
output: html_document
institute: "University of Wisconsin-River Falls"
department: "College of Business and Economics"
short-author: "Kelly"
short-date: ''
short-institute: "UWRF"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if(!require(devtools)) {
  install.packages("devtools")
}
if(!require(tutorial)) {
  devtools::install_github("datacamp/tutorial")
  library(tutorial)
}

tutorial::go_interactive(greedy = F, height = 600)
```


## In this case, you will practice using R, Rstudio Cloud, and RMarkdown.

To complete this case, use the link to the RStudio Cloud Project below. Within that project, you will find an RMarkdown file named CaseXX.Rmd, where "XX" will be replaced by the current case number. Open this file and follow the directions therein. Once you have completed the case, knit the RMarkdown file to an MS Word document. Submit the knitted docx file below. 

To access the case project, you need to join the class workspace if you have not done so already: [http://tiny.cc/ECON730-ASSIGNMENT](http://tiny.cc/ECON730-ASSIGNMENT){target=_blank}.

The case is accessible via this [RStudio Cloud Project](https://posit.cloud/spaces/404391/content/6370457){target=_blank}.

### Part 1.Basic commands.

Calculate the following using R. Store each result in a variable named a, b, c, etc.
 
1. Find the sum of two and three. Store your result in the variable `a` using the assignment operator, `<-`.
2. Find the difference between five and eight. Store your result in the variable `b`
3. Find the product of three and five. Store your result in the variable `c`
4. Use the `sqrt()` function to find the square root of four. Store your result in the variable `d`


### Part 2. Logical tests

Use R to answer the following true/false questions.
 
For this problem, let a = 5, b = 2, c = 5, d = "five", e = "two" , and f = "Two", g = TRUE.

1. a = d
2. a = b + 3 and a = c
3. e = f
4. a = b + 3 or a = c
5. d = "five"
6. a != c
7. a < 10 or a >= 5
8. g is false


