```{r data generation, echo = FALSE, results = "hide"}
## DATA GENERATION
data.issue <- "linear"#sample(c("linear","nonlinear","heteroscedasticity","outlier"),1)
linear <- data.issue == "linear"
nonlinear <- data.issue == "nonlinear"
heteroscedasticity <- data.issue == "heteroscedasticity"
outlier <- data.issue == "outlier"

Q <- sample(1:4,1)

N <- 10
NL <- 0
B0 <- sample(c(-10:-1,1:10),1)
B1 <- sample((-50:50)/10,1)
noise <- sample(c(.5,1,1.5,2),1)
X <- sample(seq(1,100,by=0.1),N)
sigma <- abs(noise * sd(X))
E <- rnorm(n = N,mean = 0,sd = sigma)
Y <- round(B0 + B1*X + E,1)

model.data = data.frame(X,Y)
model.lm <- lm(Y~X,data=model.data)
model.summ <- summary(model.lm) 
 
q.text <- list(
  'coef' = "What is the coefficient on $X$?",
  'p.value' = "What is the p-value of the significance test of the coefficient on $X$?",
  'r2'  = "What is $r^2$ for the model?",
  'f' =   "What is the $f-statistic$ for the model?"
)

q.ans <- list(
  'coef' = model.summ$coefficients[2,1],
  'p.value' = model.summ$coefficients[2,4],
  'r2'  = model.summ$r.squared,
  'f' =   model.summ$fstatistic[1]
)

q.solution <- list(
  'coef' = paste0("The coefficient on $X$ is ", fmt(model.summ$coefficients[2,1], 3), "."),
  'p.value' = paste0("The p-value of the significance test of the coefficient on $X$ is ",
                     fmt(model.summ$coefficients[2,4],3)),
  'r2'  = paste0("$r^2$ for the model is ",
                 fmt(model.summ$r.squared,3)),
  'f' = paste0("The $f-statistic$ for the model is ",
               fmt(model.summ$fstatistic[1],3))
)


```



Question
========

Use the following data to estimate the linear regression of $Y$ on $X$. Then answer the question below.

`r kable(model.data)`


```{r, echo=FALSE,results='asis'}
code <- paste0(
"model.data <- data.frame(\n",
"\tX = c(", paste(X,collapse = ", "),"),\n",
"\tY = c(", paste(Y,collapse = ", "),")\n",
")"
) %>% rdrr.io()
```

**Question:**

`r q.text[[Q]]`

Solution
========
`r q.solution[[Q]]`

Meta-information
================
extype: num
exsolution: `r fmt(q.ans[[Q]], 3)`
exname: ols2
extol: `r fmt(ex_tol, 3)`