```{r data generation, echo = FALSE, results = "hide"}
## DATA GENERATION
data.issue <- sample(c("linear","nonlinear","heteroscedasticity","outlier"),1)
linear <- data.issue == "linear"
nonlinear <- data.issue == "nonlinear"
heteroscedasticity <- data.issue == "heteroscedasticity"
outlier <- data.issue == "outlier"

NL <- 0
B0 <- sample(c(-10:-1,1:10),1)
B1 <- sample((-50:50)/10,1)
noise <- sample(c(.5,1,1.5,2),1)
X <- sample(seq(1,100,by=0.1),100)
sigma <- abs(noise * sd(X))
E <- rnorm(n = 100,mean = 0,sd = sigma)
Y <- B0 + B1*X + E
sim.data <- data.frame(X,Y,E)

if(data.issue == "nonlinear"){
  nonlinear <- TRUE
  B2 <- sample(c(runif(n = 1,min = -.04,max = -.03),runif(n = 1,min = .03,max = .04)),1)
  if(sign(B1)==sign(B2)) B2 <- -1*B2
  NL <- 1
  Y <- B0 + B1*X + B2*(X^2) + E
  sim.data <- data.frame(X,Y,E)
  test <- lm(Y~X+I(X^2),data=sim.data) %>% summary()
  if(test$coefficients[3,4]>0.005){
    NL <- 0
    nonlinear <- FALSE
    linear <- TRUE
    Y <- B0 + B1*X + E
    sim.data <- data.frame(X,Y,E)
  }
}

if(data.issue == "heteroscedasticity" & abs(cor(X,Y)) > 0.75){
  heteroscedasticity <- TRUE
  sigma <- abs(noise * sd(X) * seq(.25,2.5,length.out = 100))
  X <- sort(X,decreasing = runif(1)<.05)
  E <- rnorm(n=100, mean = 0,sd = sigma)
  Y <- B0 + B1*X + E
  sim.data <- data.frame(X,Y,E)
  test <- lm(Y~X,data=sim.data) %>% summary()
  if(test$coefficients[2,4]>0.05){
    heteroscedasticity <- FALSE
    sigma <- abs(noise * sd(X))
    E <- rnorm(n = 100,mean = 0,sd = sigma)
    Y <- B0 + B1*X + E
    sim.data <- data.frame(X,Y,E)
  }
} else {
  heteroscedasticity <- FALSE
}

if(data.issue == "outlier" & abs(cor(X,Y)) > 0.5){
  outlier <- TRUE
  Y.sd <- sd(Y)
  j <- sample(1:length(Y),1)
  Y[j] = 4*sign(Y[j])*Y.sd + B0 + B1*X[j]
  sim.data <- data.frame(X,Y,E)
} else {
  outlier <- FALSE
}

r <- cor(X,Y)

## QUESTION/ANSWER GENERATION
questions <- character(4)
solutions <- logical(4)
explanations <- character(4)


## Question 1
if (runif(1) < 0.5) {
  questions[1] <- "The data appears to exhibit a linear relationship."
  solutions[1] <- linear
  explanations[1] <- "Scatterplots with a linear pattern have points that seem to generally fall along a line while nonlinear patterns seem to follow along some curve."
} else {
  questions[1] <- "The data appears to exhibit a non-linear relationship."
  solutions[1] <- nonlinear
  explanations[1] <- "Scatterplots with a linear pattern have points that seem to generally fall along a line while nonlinear patterns seem to follow along some curve."
}

if (abs(r) < 0.2) {
  questions[1] <- "The data appears to exhibit an extremmly low correlation; thus, we cannot determine if any relationship exists."
  solutions[1] <- TRUE
  explanations[1] <- "The scatterplot shows haphazard points that follow no direction or pattern. A scatterplot with no correlation has data that does not follow a pattern."
}


## Question 2
if (runif(1) < 0.5) {
  questions[2] <- "The absolute value of the correlation coefficient is at least $0.8$."
  solutions[2] <- abs(r) >= 0.8
} else {
  questions[2] <- "The absolute value of the correlation coefficient is at most $0.8$."
  solutions[2] <- abs(r) <= 0.8
}
explanations[2] <- if(abs(r) >= 0.9) {
  paste("A strong association between the variables is given in the scatterplot.",
        "Hence the absolute value of the correlation coefficient is close to $1$",
        "and therefore larger than $0.8$.") 
  } else if (abs(r) <= 0.2) {
    paste("No (or very weak) association between the variables is observed in the scatterplot.",
          "This implies a correlation coefficient close to $0$.") 
  } else paste("Only a weak association between the variables is observable in the scatterplot.",
               "This implies a correlation coefficient with an absolute value smaller than $0.8$.")

## Question 3
  questions[3] <- "The data appears to have at least one outlier."
  solutions[3] <- outlier
  explanations[3] <- "Unusual observations have values that are not necessarily extreme, but they do not fit the observed relationship."

if (runif(1) < 0.5) {
  questions[4] <- "The data appears to exhibit a heteroscedasticity, i.e. heterogeneity of variance."
  solutions[4] <- heteroscedasticity
  explanations[4] <-  "Heteroscedasticity (also spelled heteroskedasticity) refers to the circumstance in which the variability of a variable is unequal across the range of values of a second variable."
} else {
  questions[4] <- "The data appears to exhibit a homoscedasticity, i.e. homogeneity of variance."
  solutions[4] <- !heteroscedasticity
  explanations[4] <- "Heteroscedasticity (also spelled heteroskedasticity) refers to the circumstance in which the variability of a variable is unequal across the range of values of a second variable."
}
  
if(length(unique(solutions)) == 1){
  questions[3] <- "The data does not appears to have any outliers."
  solutions[3] <- !outlier
  explanations[3] <- "Unusual observations have values that are not necessarily extreme, but they do not fit the observed relationship."
} 


## permute order of solutions/questions
o <- sample(1:4)
questions <- questions[o]
solutions <- solutions[o]
explanations <- explanations[o]  
```

Question
========

The following figure shows a scatterplot. Which of the following statements are correct?

```{r scatterplot, echo = FALSE, results = "hide", fig.height = 5, fig.width = 6, fig.path = "", fig.cap = ""}
plot(X, Y)
```

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```


Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(ifelse(solutions, "True", "False"), explanations, markup = "markdown")
```


Meta-information
================
extype: mchoice
exsolution: `r mchoice2string(solutions)`
exname: Scatterplot
