```{r data generation, echo = FALSE, results = "hide"}
## DATA GENERATION
data.issue <- "linear" #sample(c("linear","nonlinear","heteroscedasticity","outlier"),1)
linear <- data.issue == "linear"
nonlinear <- data.issue == "nonlinear"
heteroscedasticity <- data.issue == "heteroscedasticity"
outlier <- data.issue == "outlier"

conf.level <- sample(c(0.9,0.95,0.99),1)

N <- sample(30:150,1)
NL <- 0
B0 <- sample(c(-10:-1,1:10),1)
B1 <- sample((-50:50)/10,1)
noise <- sample(c(.5,1,1.5,2),1)
X <- sample(seq(1,100,by=0.1),N)
sigma <- abs(noise * sd(X))
E <- rnorm(n = N,mean = 0,sd = sigma)

if(runif(1)<.5) Y <- B0 + B1*X + E else Y <- E
sim.data <- data.frame(X,Y,E)

if(data.issue == "nonlinear"){
  nonlinear <- TRUE
  B2 <- sample(c(runif(n = 1,min = -.04,max = -.03),runif(n = 1,min = .03,max = .04)),1)
  if(sign(B1)==sign(B2)) B2 <- -1*B2
  NL <- 1
  Y <- B0 + B1*X + B2*(X^2) + E
  sim.data <- data.frame(X,Y,E)
  test <- lm(Y~X+I(X^2),data=sim.data) %>% summary()
  if(test$coefficients[3,4]>0.005){
    NL <- 0
    nonlinear <- FALSE
    linear <- TRUE
    Y <- B0 + B1*X + E
    sim.data <- data.frame(X,Y,E)
  }
}

if(data.issue == "heteroscedasticity" & abs(cor(X,Y)) > 0.75){
  heteroscedasticity <- TRUE
  sigma <- abs(noise * sd(X) * seq(.25,2.5,length.out = N))
  X <- sort(X,decreasing = runif(1)<.05)
  E <- rnorm(n=N, mean = 0,sd = sigma)
  Y <- B0 + B1*X + E
  sim.data <- data.frame(X,Y,E)
  test <- lm(Y~X,data=sim.data) %>% summary()
  if(test$coefficients[2,4]>0.05){
    heteroscedasticity <- FALSE
    sigma <- abs(noise * sd(X))
    E <- rnorm(n = N,mean = 0,sd = sigma)
    Y <- B0 + B1*X + E
    sim.data <- data.frame(X,Y,E)
  }
} else {
  heteroscedasticity <- FALSE
}

if(data.issue == "outlier" & abs(cor(X,Y)) > 0.5){
  outlier <- TRUE
  Y.sd <- sd(Y)
  j <- sample(1:length(Y),1)
  Y[j] = 4*sign(Y[j])*Y.sd + B0 + B1*X[j]
  sim.data <- data.frame(X,Y,E)
} else {
  outlier <- FALSE
}

r <- cor(X,Y)
lm.output <- list(
  "linear" = lm(Y~X,data=sim.data) %>% summary(),
  "quadratic" = lm(Y~X+I(X^2),data=sim.data) %>% summary()
) 


## QUESTION/ANSWER GENERATION
questions <- character(4)
solutions <- logical(4)
explanations <- character(4)


## Question 1
if (runif(1) < 0.5) {
  questions[1] <- paste0(
    "The regression equation implied by the output above is approximately ",
    "$\\hat{Y} = ",fmt(lm.output[["linear"]]$coefficients[1,1], 3), " + ",
    fmt(lm.output[["linear"]]$coefficients[2,1], 3),"\\times X$. ",
    "[Link to Text Book](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)/15%3A_Linear_Regression/15.02%3A_Estimating_a_Linear_Regression_Model){target=\"blank\"}")
  solutions[1] <- TRUE
  explanations[1] <- paste0(
    "The regression equation implied by the output above is approximately ",
    "$\\hat{Y} = ",fmt(lm.output[["linear"]]$coefficients[1,1], 3), " + ",
    fmt(lm.output[["linear"]]$coefficients[2,1], 3),"\\times X$. ",
    "[Link to Text Book](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)/15%3A_Linear_Regression/15.02%3A_Estimating_a_Linear_Regression_Model){target=\"blank\"}")
} else {
  questions[1] <- paste0(
    "The regression equation implied by the output above is approximately ",
    "$\\hat{Y} = ",fmt(lm.output[["linear"]]$coefficients[2,1], 3), " + ",
    fmt(lm.output[["linear"]]$coefficients[1,1], 3),"\\times X$. ",
    "[Link to Text Book](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)/15%3A_Linear_Regression/15.02%3A_Estimating_a_Linear_Regression_Model){target=\"blank\"}")
  solutions[1] <- FALSE
  explanations[1] <- paste0(
    "The regression equation implied by the output above is approximately ",
    "$\\hat{Y} = ",fmt(lm.output[["linear"]]$coefficients[1,1], 3), " + ",
    fmt(lm.output[["linear"]]$coefficients[2,1], 3),"\\times X$. ",
    "[Link to Text Book](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)/15%3A_Linear_Regression/15.02%3A_Estimating_a_Linear_Regression_Model){target=\"blank\"}")
}

## Question 2
if (runif(1) < 0.5) {
  questions[2] <- paste0("The number of observations in the data sample used to estimate the model is equal to ",fmt(lm.output[["linear"]]$df[2]+2,0),".")
  solutions[2] <- TRUE
  explanations[2] <- "The number of observations in the data sample used to estimate the model is equal to the degrees of freedom pluse the number of parameters estimated."
} else {
  questions[2] <- paste0("The number of observations in the data sample used to estimate the model is equal to ",fmt(lm.output[["linear"]]$df[2],0),".")
  solutions[2] <- FALSE
  explanations[2] <- "The number of observations in the data sample used to estimate the model is equal to the degrees of freedom pluse the number of parameters estimated."
}

## Question 3
  questions[3] <- paste0("The coefficient on $X$ is statistically significant at the ",
                         fmt(conf.level,2),
                         " confidence level.")
  solutions[3] <- lm.output[["linear"]]$coefficients[2,4] <= (1-conf.level)
  
  if(solutions[3]) {
    explanations[3] <- paste0("The p-value for the coefficient on $X$,",
                              fmt(lm.output[["linear"]]$coefficients[2,4],4),
                              ", is less than (1 - ", 
                              fmt(conf.level,2), 
                              "); thus, the coefficient on $X$ is statistically significant. ",
                              "[Link to Text Book](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)/15%3A_Linear_Regression/15.05%3A_Hypothesis_Tests_for_Regression_Models){target=\"blank\"}")
  } else {
    explanations[3] <- paste0("The p-value for the coefficient on $X$,",
                              fmt(lm.output[["linear"]]$coefficients[2,4],4),
                              ", is greater than (1 - ", 
                              fmt(conf.level,2), 
                              "); thus, the coefficient on $X$ is not statistically significant. ",
                              "[Link to Text Book](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)/15%3A_Linear_Regression/15.05%3A_Hypothesis_Tests_for_Regression_Models){target=\"blank\"}")
  }
    
## Question 3
  questions[4] <- paste0("The intercept is significantly different from zero at the ",
                         fmt(conf.level,2),
                         " confidence level.")
  solutions[4] <- lm.output[["linear"]]$coefficients[1,4] <= (1-conf.level)
  
  if(solutions[4]) {
    explanations[4] <- paste0("The p-value for the intercept ,",
                              fmt(lm.output[["linear"]]$coefficients[1,4],4),
                              ", is less than (1 - ", 
                              fmt(conf.level,2), 
                              "); thus, the intercept is significantly different from zero. ",
                              "[Link to Text Book](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)/15%3A_Linear_Regression/15.05%3A_Hypothesis_Tests_for_Regression_Models){target=\"blank\"}")
  } else {
    explanations[4] <- paste0("The p-value for the intercept ,",
                              fmt(lm.output[["linear"]]$coefficients[1,4],4),
                              ", is greater than (1 - ", 
                              fmt(conf.level,2), 
                              "); thus, the intercept is significantly different from zero. ",
                              "[Link to Text Book](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)/15%3A_Linear_Regression/15.05%3A_Hypothesis_Tests_for_Regression_Models){target=\"blank\"}")
  }
  
if(length(unique(solutions)) == 1){
 if (!solutions[1]) {
  questions[1] <- paste0(
    "The regression equation implied by the output above is approximately ",
    "$\\hat{Y} = ",fmt(lm.output[["linear"]]$coefficients[1,1], 3), " + ",
    fmt(lm.output[["linear"]]$coefficients[2,1], 3),"\\times X$. ",
    "[Link to Text Book](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)/15%3A_Linear_Regression/15.02%3A_Estimating_a_Linear_Regression_Model){target=\"blank\"}")
  solutions[1] <- TRUE
  explanations[1] <- paste0(
    "The regression equation implied by the output above is approximately ",
    "$\\hat{Y} = ",fmt(lm.output[["linear"]]$coefficients[1,1], 3), " + ",
    fmt(lm.output[["linear"]]$coefficients[2,1], 3),"\\times X$. ",
    "[Link to Text Book](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)/15%3A_Linear_Regression/15.02%3A_Estimating_a_Linear_Regression_Model){target=\"blank\"}")
} else {
  questions[1] <- paste0(
    "The regression equation implied by the output above is approximately ",
    "$\\hat{Y} = ",fmt(lm.output[["linear"]]$coefficients[2,1], 3), " + ",
    fmt(lm.output[["linear"]]$coefficients[1,1], 3),"\\times X$. ",
    "[Link to Text Book](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)/15%3A_Linear_Regression/15.02%3A_Estimating_a_Linear_Regression_Model){target=\"blank\"}")
  solutions[1] <- FALSE
  explanations[1] <- paste0(
    "The regression equation implied by the output above is approximately ",
    "$\\hat{Y} = ",fmt(lm.output[["linear"]]$coefficients[1,1], 3), " + ",
    fmt(lm.output[["linear"]]$coefficients[2,1], 3),"\\times X$. ",
    "[Link to Text Book](https://stats.libretexts.org/Bookshelves/Applied_Statistics/Book%3A_Learning_Statistics_with_R_-_A_tutorial_for_Psychology_Students_and_other_Beginners_(Navarro)/15%3A_Linear_Regression/15.02%3A_Estimating_a_Linear_Regression_Model){target=\"blank\"}")
}
} 


## permute order of solutions/questions
o <- sample(1:4)
questions <- questions[o]
solutions <- solutions[o]
explanations <- explanations[o]  
```

Question
========

The following shows the output of regressing Y on X. Which of the following statements are correct?

```{r regression_output, echo = FALSE}
lm.output[["linear"]]
```

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```


Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(ifelse(solutions, "True", "False"), explanations, markup = "markdown")
```


Meta-information
================
extype: mchoice
exsolution: `r mchoice2string(solutions)`
exname: Scatterplot
