```{r data generation, echo = FALSE, results = "hide"}
## DATA GENERATION
data.issue <-sample(c("linear","nonlinear","heteroscedasticity","outlier"),1)
linear <- data.issue == "linear"
nonlinear <- data.issue == "nonlinear"
heteroscedasticity <- data.issue == "heteroscedasticity"
outlier <- data.issue == "outlier"

conf.level <- sample(c(0.9,0.95,0.99),1)

N <- sample(30:150,1)
NL <- 0
B0 <- sample(c(-10:-1,1:10),1)
B1 <- sample((-50:50)/10,1)
noise <- sample(c(.5,1,1.5,2),1)
X <- sample(seq(1,100,by=0.1),N)
sigma <- abs(noise * sd(X))
E <- rnorm(n = N,mean = 0,sd = sigma)

if(runif(1)<.5) Y <- B0 + B1*X + E else Y <- E
sim.data <- data.frame(X,Y,E)

if(data.issue == "nonlinear"){
  nonlinear <- TRUE
  B2 <- sample(c(runif(n = 1,min = -.04,max = -.03),runif(n = 1,min = .03,max = .04)),1)
  if(sign(B1)==sign(B2)) B2 <- -1*B2
  NL <- 1
  Y <- B0 + B1*X + B2*(X^2) + E
  sim.data <- data.frame(X,Y,E)
  test <- lm(Y~X+I(X^2),data=sim.data) %>% summary()
  if(test$coefficients[3,4]>0.005){
    NL <- 0
    nonlinear <- FALSE
    linear <- TRUE
    Y <- B0 + B1*X + E
    sim.data <- data.frame(X,Y,E)
  }
}

if(data.issue == "heteroscedasticity" & abs(cor(X,Y)) > 0.75){
  heteroscedasticity <- TRUE
  sigma <- abs(noise * sd(X) * seq(.25,2.5,length.out = N))
  X <- sort(X,decreasing = runif(1)<.05)
  E <- rnorm(n=N, mean = 0,sd = sigma)
  Y <- B0 + B1*X + E
  sim.data <- data.frame(X,Y,E)
  test <- lm(Y~X,data=sim.data) %>% summary()
  if(test$coefficients[2,4]>0.05){
    heteroscedasticity <- FALSE
    sigma <- abs(noise * sd(X))
    E <- rnorm(n = N,mean = 0,sd = sigma)
    Y <- B0 + B1*X + E
    sim.data <- data.frame(X,Y,E)
  }
} else {
  heteroscedasticity <- FALSE
}

if(data.issue == "outlier" & abs(cor(X,Y)) > 0.5){
  outlier <- TRUE
  Y.sd <- sd(Y)
  j <- sample(1:length(Y),1)
  Y[j] = 4*sign(Y[j])*Y.sd + B0 + B1*X[j]
  sim.data <- data.frame(X,Y,E)
} else {
  outlier <- FALSE
}

r <- cor(X,Y)
lm.output <- list(
  "linear" = lm(Y~X,data=sim.data) %>% summary(),
  "model" = lm(Y~X,data=sim.data)
) 


## QUESTION/ANSWER GENERATION
questions <- character(4)
solutions <- logical(4)
explanations <- character(4)

questions[1] <- "The residual vs fit plot above seems to indicate that the relationship between the dependent and independent variables is linear."
solutions[1] <- linear
explanations[1] <- "This plot is a classical example of a well-behaved residuals vs. fits plot, i.e. (i) the residuals bounce randomly around the 0 line, (ii) the residuals roughly form a horizontal band around the 0 line, and (iii) no one residual stands out from the basic random pattern of residuals."
  
questions[2] <- "The residual vs fit plot above seems to indicate that the relationship between the dependent and independent variables is non-linear."
solutions[2] <- nonlinear
explanations[2] <- "The residual vs fit plot ehibit a non-linear relationship, which indicates that the relationship between the dependent and independent variables is non-linear."
  
questions[3] <- "The residual vs fit plot above seems to indicate the presence of heteroscedasticity."
solutions[3] <- heteroscedasticity
explanations[3] <- "The spread of the residuls changes as the fitted value changres. This is heteroscedasticity."

questions[4] <- "The residual vs fit plot above seems to indicate that the presence of an outlier"
solutions[4] <- outlier
explanations[4] <- "At least one residual stands out from the basic random pattern of residuals."

## permute order of solutions/questions
o <- sample(1:4)
questions <- questions[o]
solutions <- solutions[o]
explanations <- explanations[o]  
```

Question
========

The following is a residuals vs fitted plot arising from a linear regression model. Which of the following statements are correct?


```{r, echo = FALSE, results = "hide", fig.height = 5, fig.width = 6, fig.path = "", fig.cap = ""}
plot(lm.output$model,which = 1)
```




```{r questionlist, echo = FALSE, results = "asis"}
answerlist(questions, markup = "markdown")
```


Solution
========

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist(ifelse(solutions, "True", "False"), explanations, markup = "markdown")
```


Meta-information
================
extype: mchoice
exsolution: `r mchoice2string(solutions)`
exname: Scatterplot
